// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.19.1
// source: index.proto

/* eslint-disable */

export const protobufPackage = '';
