// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.19.1
// source: question.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'solana_quiz.v1';

export interface GetQuestionsRequest {
  quizId: number;
}

export interface QuizQuestionOption {
  id: number;
  option: string;
  createdAt: string;
}

export interface QuizQuestion {
  id: number;
  question: string;
  answer: string;
  options: QuizQuestionOption[];
  createdAt: string;
}

export interface GetQuestionsResponse {
  questions: QuizQuestion[];
}

function createBaseGetQuestionsRequest(): GetQuestionsRequest {
  return { quizId: 0 };
}

export const GetQuestionsRequest: MessageFns<GetQuestionsRequest> = {
  encode(
    message: GetQuestionsRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.quizId !== 0) {
      writer.uint32(8).int32(message.quizId);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): GetQuestionsRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetQuestionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.quizId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetQuestionsRequest {
    return {
      quizId: isSet(object.quizId) ? globalThis.Number(object.quizId) : 0,
    };
  },

  toJSON(message: GetQuestionsRequest): unknown {
    const obj: any = {};
    if (message.quizId !== 0) {
      obj.quizId = Math.round(message.quizId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetQuestionsRequest>, I>>(
    base?: I,
  ): GetQuestionsRequest {
    return GetQuestionsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetQuestionsRequest>, I>>(
    object: I,
  ): GetQuestionsRequest {
    const message = createBaseGetQuestionsRequest();
    message.quizId = object.quizId ?? 0;
    return message;
  },
};

function createBaseQuizQuestionOption(): QuizQuestionOption {
  return { id: 0, option: '', createdAt: '' };
}

export const QuizQuestionOption: MessageFns<QuizQuestionOption> = {
  encode(
    message: QuizQuestionOption,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.option !== '') {
      writer.uint32(18).string(message.option);
    }
    if (message.createdAt !== '') {
      writer.uint32(26).string(message.createdAt);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): QuizQuestionOption {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuizQuestionOption();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.option = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuizQuestionOption {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      option: isSet(object.option) ? globalThis.String(object.option) : '',
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : '',
    };
  },

  toJSON(message: QuizQuestionOption): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.option !== '') {
      obj.option = message.option;
    }
    if (message.createdAt !== '') {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuizQuestionOption>, I>>(
    base?: I,
  ): QuizQuestionOption {
    return QuizQuestionOption.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuizQuestionOption>, I>>(
    object: I,
  ): QuizQuestionOption {
    const message = createBaseQuizQuestionOption();
    message.id = object.id ?? 0;
    message.option = object.option ?? '';
    message.createdAt = object.createdAt ?? '';
    return message;
  },
};

function createBaseQuizQuestion(): QuizQuestion {
  return { id: 0, question: '', answer: '', options: [], createdAt: '' };
}

export const QuizQuestion: MessageFns<QuizQuestion> = {
  encode(
    message: QuizQuestion,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.question !== '') {
      writer.uint32(18).string(message.question);
    }
    if (message.answer !== '') {
      writer.uint32(26).string(message.answer);
    }
    for (const v of message.options) {
      QuizQuestionOption.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.createdAt !== '') {
      writer.uint32(42).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuizQuestion {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuizQuestion();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.answer = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.options.push(
            QuizQuestionOption.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuizQuestion {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      question: isSet(object.question)
        ? globalThis.String(object.question)
        : '',
      answer: isSet(object.answer) ? globalThis.String(object.answer) : '',
      options: globalThis.Array.isArray(object?.options)
        ? object.options.map((e: any) => QuizQuestionOption.fromJSON(e))
        : [],
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : '',
    };
  },

  toJSON(message: QuizQuestion): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.question !== '') {
      obj.question = message.question;
    }
    if (message.answer !== '') {
      obj.answer = message.answer;
    }
    if (message.options?.length) {
      obj.options = message.options.map((e) => QuizQuestionOption.toJSON(e));
    }
    if (message.createdAt !== '') {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuizQuestion>, I>>(
    base?: I,
  ): QuizQuestion {
    return QuizQuestion.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuizQuestion>, I>>(
    object: I,
  ): QuizQuestion {
    const message = createBaseQuizQuestion();
    message.id = object.id ?? 0;
    message.question = object.question ?? '';
    message.answer = object.answer ?? '';
    message.options =
      object.options?.map((e) => QuizQuestionOption.fromPartial(e)) || [];
    message.createdAt = object.createdAt ?? '';
    return message;
  },
};

function createBaseGetQuestionsResponse(): GetQuestionsResponse {
  return { questions: [] };
}

export const GetQuestionsResponse: MessageFns<GetQuestionsResponse> = {
  encode(
    message: GetQuestionsResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.questions) {
      QuizQuestion.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): GetQuestionsResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetQuestionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.questions.push(QuizQuestion.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetQuestionsResponse {
    return {
      questions: globalThis.Array.isArray(object?.questions)
        ? object.questions.map((e: any) => QuizQuestion.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetQuestionsResponse): unknown {
    const obj: any = {};
    if (message.questions?.length) {
      obj.questions = message.questions.map((e) => QuizQuestion.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetQuestionsResponse>, I>>(
    base?: I,
  ): GetQuestionsResponse {
    return GetQuestionsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetQuestionsResponse>, I>>(
    object: I,
  ): GetQuestionsResponse {
    const message = createBaseGetQuestionsResponse();
    message.questions =
      object.questions?.map((e) => QuizQuestion.fromPartial(e)) || [];
    return message;
  },
};

export interface QuestionService {
  GetQuestions(request: GetQuestionsRequest): Promise<GetQuestionsResponse>;
}

export const QuestionServiceServiceName = 'solana_quiz.v1.QuestionService';
export class QuestionServiceClientImpl implements QuestionService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QuestionServiceServiceName;
    this.rpc = rpc;
    this.GetQuestions = this.GetQuestions.bind(this);
  }
  GetQuestions(request: GetQuestionsRequest): Promise<GetQuestionsResponse> {
    const data = GetQuestionsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'GetQuestions', data);
    return promise.then((data) =>
      GetQuestionsResponse.decode(new BinaryReader(data)),
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array,
  ): Promise<Uint8Array>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
