// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.19.1
// source: quiz.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from '@bufbuild/protobuf/wire';

export const protobufPackage = 'solana_quiz.v1';

export interface GetQuizIdRequest {}

export interface GetQuizIdResponse {
  quizId: number;
}

function createBaseGetQuizIdRequest(): GetQuizIdRequest {
  return {};
}

export const GetQuizIdRequest: MessageFns<GetQuizIdRequest> = {
  encode(
    _: GetQuizIdRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetQuizIdRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetQuizIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetQuizIdRequest {
    return {};
  },

  toJSON(_: GetQuizIdRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetQuizIdRequest>, I>>(
    base?: I,
  ): GetQuizIdRequest {
    return GetQuizIdRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetQuizIdRequest>, I>>(
    _: I,
  ): GetQuizIdRequest {
    const message = createBaseGetQuizIdRequest();
    return message;
  },
};

function createBaseGetQuizIdResponse(): GetQuizIdResponse {
  return { quizId: 0 };
}

export const GetQuizIdResponse: MessageFns<GetQuizIdResponse> = {
  encode(
    message: GetQuizIdResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.quizId !== 0) {
      writer.uint32(8).int32(message.quizId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetQuizIdResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetQuizIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.quizId = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetQuizIdResponse {
    return {
      quizId: isSet(object.quizId) ? globalThis.Number(object.quizId) : 0,
    };
  },

  toJSON(message: GetQuizIdResponse): unknown {
    const obj: any = {};
    if (message.quizId !== 0) {
      obj.quizId = Math.round(message.quizId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetQuizIdResponse>, I>>(
    base?: I,
  ): GetQuizIdResponse {
    return GetQuizIdResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetQuizIdResponse>, I>>(
    object: I,
  ): GetQuizIdResponse {
    const message = createBaseGetQuizIdResponse();
    message.quizId = object.quizId ?? 0;
    return message;
  },
};

export interface QuizService {
  GetQuizId(request: GetQuizIdRequest): Promise<GetQuizIdResponse>;
}

export const QuizServiceServiceName = 'solana_quiz.v1.QuizService';
export class QuizServiceClientImpl implements QuizService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || QuizServiceServiceName;
    this.rpc = rpc;
    this.GetQuizId = this.GetQuizId.bind(this);
  }
  GetQuizId(request: GetQuizIdRequest): Promise<GetQuizIdResponse> {
    const data = GetQuizIdRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, 'GetQuizId', data);
    return promise.then((data) =>
      GetQuizIdResponse.decode(new BinaryReader(data)),
    );
  }
}

interface Rpc {
  request(
    service: string,
    method: string,
    data: Uint8Array,
  ): Promise<Uint8Array>;
}

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
