{
 "title": "Node.js App Metrics",
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "HTTP Latency p50/p95/p99",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p50_seconds",
     "legendFormat": "p50"
    },
    {
     "expr": "nodejs_eventloop_lag_p90_seconds",
     "legendFormat": "p90"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Heap Usage %",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes / process_heap_bytes * 100",
     "legendFormat": "heap % of reserved"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 6 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "RSS" }
   ]
  },
  {
   "title": "GC per second",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{kind=\"minor\"}[1m])",
     "legendFormat": "minor GC"
    },
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{kind=\"major\"}[1m])",
     "legendFormat": "major GC"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU cores"
    }
   ]
  },
  {
   "title": "Active Handles & FDs",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 6 },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "handles" },
    { "expr": "process_open_fds", "legendFormat": "open fds" }
   ]
  }
 ]
}